name: Delivery Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  landing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy Landing Page 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: landing
          branch: gh-pages

  build:
    needs: landing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm install

      - name: Build & Publish App 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npx electron-builder --publish always
